Linux Bits for 1.02 (#201)
* OpenGL/screenCapture: fix random crashes on init

On startup, screenCapture will cause random crashed because
of uninitialized m_capures member.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* Fix crashes in Allocator code

When freeing items with allocator_free, at some point all
members of the Allocator become ALLOC_INVALID_PTR, then
allcator_getHead crashes due to trying to derefence an invalid
Allocator::head pointer.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* Explicity initialize Archive type at class creation time

The GobMemoryArchive does not define an ARCHIVE_GOB type anywhere.
To fix this, add a new constructor to the base class to set the
archive type at instantiation time.
This fixes a crash on Linux with Mods (quitting while running a
mod, or loading a savegame away from a mod, where the memory gob
freeing causes a crash).

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* MIDI: fix length of the PROGRAM_CHANGE message

TFE sends 3 bytes for every MIDI message; however there are
some, among them PROGRAM CHANGE (to define instrument to use),
which only have 1 argument byte instead of 2.
The Linux ALSA midi parser gets confused by the 3rd byte.
So adhere to MIDI and only send 2 byte messages for PROGRAM CHANGE.
(there are other midi messages with only 2 bytes, but TFE doesn't
use them).

This fixes the piano-only output on Linux.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* Fix ImGui usage bug in Input Settings page

There are 2 BeginChild() that are close with End(), fix that.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* imuse: fix int to pointer cast warning

gcc and clang complain about the 2nd parameter to ImSetSoundTrigger();
Fix with a reinterpret_cast<>

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* fix build with clang

clang-15 stops build with this error:
TheForceEngine/TFE_Jedi/IMuse/imDigitalSound.cpp:61:13: error: copying variable of type 'atomic_s32' (aka 'atomic<int>') invokes deleted constructor
        atomic_s32 s_digitalPause = 0;

Remove the explicit initialization.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* replace windows-only functions with portable ones

- _strlwr()/_strupr() are Windows CRT only, roll our own and use them
  throughout the codebase.
- replace the windows-oly *_s() string functions with portable
  equivalents

* Archives: fix size of members on 64bit linux/unix

Windows and Linux/Posix have different opinions on the length of
"(unsigned) long" and other C types on 64bit:  Windows compilers
keep 32bit and 64bit identical, while they differ on POSIX.

Work around this by using the explicitly sized types, and letting
the compiler sort it out.

* rework some macro usage to make gcc/clang happy.

gcc-13 is picky about preprocessor macros and missing arguments
in place of VA_ARGS.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* include missing C++ header files

unlike previous versions, gcc-13 does no longer implicitly include
a lot of c++ header files.  Add them to the files that need them.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* fix multiple definitions in TFE_DarkForces/GameUI/pda.cpp

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* RenderBackend: call SDL_SetWindowFullscreen

Fixes fullscreen on Linux Window managers.

* fix template specialization errors in filestream/memorystream

GCC complains about an invalid explicit specialization outside
a namespace scope:
filestream.h:67:19: error: explicit specialization in non-namespace scope 'class FileStream'

Work around by explicitly implementing the template.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* Add posix mutexes to audio devices support

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* Linux bits

Implement missing pieces for Linux support:
- CMake buildsystem
- posix/linux specific file- and pathhandling bits.
  this implementation also takes case-sensitivity of
  unix filesystems into account.
- add infrastructure to look up system files (shaders, doc,
  fonts, ...) independently from the main binary (for distro
  packaging).
- fix up the linux thread implementation.
- fix up 32bit target build.
- crash handler skeleton.
- can look for game data files in local Steam installation on
  multiple libraries.
  (GOG linux games do not leave trails about their installation
   paths in any central location, so gog detection is missing).

based partly on previous work by Matthew Gilmore.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* Fix remaining build warnings with default cflags

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

* Add uppercase extension filter to for file dialogs

On some Linux DEs, the native file dialog does a case sensitive
search for file extensions.  Add the uppercase extensions
LAB and GOB as well to fix at least Gnome/GTK file dialogs being
unable to select the DARK.GOB file.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

---------

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>
Co-authored-by: Matthew Gilmore <segaloco@protonmail.com>